name: Rust Build & Docs

on:
  push:
    branches: [ "master", "main" ]
    paths-ignore:
      - 'Docs/**/*.md'
      - '*.md'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Rust Cache
      uses: swatinem/rust-cache@v2
    - name: Install dependencies
      run: |
        choco install ninja
    - name: Build Release
      run: cargo build --release --verbose
    - name: Generate Version Info
      run: |
        $date = (Get-Date).ToUniversalTime().AddHours(8).ToString("yyyy-MM-dd HH:mm:ss")
        $json = @{ timestamp = $date } | ConvertTo-Json
        $json | Out-File -FilePath target/release/version_info.json -Encoding utf8
    - name: Delete Old Nightly Release
      run: |
        gh release delete nightly --yes --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Upload Nightly Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      with:
        tag_name: nightly
        name: Nightly Build
        draft: false
        prerelease: true
        files: |
          target/release/WinIsland.exe
          target/release/version_info.json
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: Page/package.json
      - name: Install dependencies
        run: cd Page && npm install
      - name: Build Docs
        run: cd Page && npm run docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Page/.vitepress/dist

  deploy-docs:
    if: github.repository == 'Eatgrapes/WinIsland'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
